'use strict';

/** Villes d'intervention — Béziers (siège) et communes dans un rayon d'environ 30 km */
const cities = [
  {
    slug: 'beziers',
    name: 'Béziers',
    dept: 'Hérault (34)',
    tag: 'Siège — rayon 30 km',
    lat: 43.341,
    lng: 3.215,
    lead: "SAR Nettoyage est basé à Béziers. Nous intervenons en centre-ville et dans tout le bassin biterrois pour le nettoyage de toiture, démoussage, traitement hydrofuge de tuiles et ravalement de façade. Devis gratuit sous 15 minutes.",
    communes: ['Centre-ville', 'Les Ayroles', 'Montimaran', 'Saint-James', 'La Madeleine', 'Deveze', 'Fraisse-sur-Agout', 'Cers'],
    img: 'service_exterior.png',
    alt: 'Nettoyage de toiture et façade à Béziers',
    cardSub: 'Siège & centre-ville',
  },
  {
    slug: 'serignan',
    name: 'Sérignan',
    dept: 'Hérault (34)',
    tag: 'À ~8 km de Béziers',
    lat: 43.283,
    lng: 3.283,
    lead: "Nettoyage de toiture et démoussage à Sérignan et sur le littoral proche. Face à l'humidité marine, aux algues et au vent de mer, nous protégeons vos tuiles et façades avec des traitements hydrofuges professionnels.",
    communes: ['Centre-ville', 'Plage', 'Pinède', 'Vignerols', 'Les Orpellières', 'Le Grand Travers'],
    img: 'img3.jpg',
    alt: 'Démoussage et nettoyage de toiture à Sérignan',
    cardSub: 'Littoral & centre',
  },
  {
    slug: 'valras-plage',
    name: 'Valras-Plage',
    dept: 'Hérault (34)',
    tag: 'À ~10 km de Béziers',
    lat: 43.25,
    lng: 3.292,
    lead: "Nettoyage de toiture et traitement anti-mousse à Valras-Plage. Spécialiste de l'entretien de toits et ravalement de façades exposées au sel marin, aux lichens et aux tempêtes. Devis gratuit.",
    communes: ['Front de mer', 'Centre', 'Les Vignes', 'La Voilière', 'Les Marines', 'Capiscol'],
    img: 'img2.jpg',
    alt: 'Nettoyage de toiture et façades à Valras-Plage',
    cardSub: 'Station balnéaire',
  },
  {
    slug: 'vias',
    name: 'Vias',
    dept: 'Hérault (34)',
    tag: 'À ~12 km de Béziers',
    lat: 43.314,
    lng: 3.417,
    lead: "Nettoyage de toiture et démoussage de tuiles à Vias, entre plage et village. Nos équipes éliminent les lichens et mousses de toit, et appliquent un traitement hydrofuge protecteur et imperméabilisant.",
    communes: ['Centre-ville', 'Vias-Plage', 'Méditerranée', 'Les Saladelles', 'Le Cap', 'Domaine de la Tour'],
    img: 'img3.jpg',
    alt: 'Démoussage de toiture à Vias',
    cardSub: 'Plage & village',
  },
  {
    slug: 'villeneuve-les-beziers',
    name: 'Villeneuve-lès-Béziers',
    dept: 'Hérault (34)',
    tag: 'À ~5 km de Béziers',
    lat: 43.318,
    lng: 3.285,
    lead: "Intervention à Villeneuve-lès-Béziers pour le nettoyage de toiture, démoussage et hydrofuge de tuiles en pavillons, résidences et copropriétés. Proximité immédiate de notre siège.",
    communes: ['Centre', 'Les Mas de la Mer', 'Capiscol', 'Les Écus', 'Domaine des Oliviers', 'Hameau de la Plage'],
    img: 'img4.webp',
    alt: 'Entretien de toiture à Villeneuve-lès-Béziers',
    cardSub: 'Agglomération biterroise',
  },
  {
    slug: 'agde',
    name: 'Agde',
    dept: 'Hérault (34)',
    tag: 'À ~27 km de Béziers',
    lat: 43.311,
    lng: 3.475,
    lead: "Nettoyage de toiture et démoussage à Agde et au Cap d'Agde. Élimination du sel, des algues et lichens sur les tuiles et application d'un traitement hydrofuge imperméabilisant de toiture.",
    communes: ["Le Grau d'Agde", 'Le Cap d\'Agde', 'Centre historique', 'Saint-Vincent', 'Tamarius', 'Richelieu'],
    img: 'service_exterior.png',
    alt: 'Nettoyage de toiture à Agde',
    cardSub: 'Cap & centre',
  },
  {
    slug: 'pezenas',
    name: 'Pézenas',
    dept: 'Hérault (34)',
    tag: 'À ~25 km de Béziers',
    lat: 43.461,
    lng: 3.423,
    lead: "Nettoyage de toiture et démoussage de tuiles anciennes à Pézenas et communes voisines. Restauration de toits historiques et traitement hydrofuge respectueux des matériaux par SAR Nettoyage.",
    communes: ['Centre historique', 'Saint-Jean', 'Nébian', 'Tourbes', 'Pomérols', 'Castelnau-de-Guers'],
    img: 'img6.jpg',
    alt: 'Démoussage et nettoyage de toiture à Pézenas',
    cardSub: 'Cité médiévale',
  },
  {
    slug: 'capestang',
    name: 'Capestang',
    dept: 'Hérault (34)',
    tag: 'À ~18 km de Béziers',
    lat: 43.328,
    lng: 3.044,
    lead: "Nettoyage de toiture, démoussage et nettoyage de gouttières à Capestang et villages du canal du Midi. Protégez votre toiture contre les infiltrations et la mousse. Devis gratuit.",
    communes: ['Centre-ville', 'Le Canal', 'Quarante', 'Poilhès', 'Montels', 'Pradelles-en-Val'],
    img: 'img4.webp',
    alt: 'Nettoyage de toiture et gouttières à Capestang',
    cardSub: 'Canal du Midi',
  },
];

const ZONE_NAV_LABEL = "Zone d'intervention";

module.exports = { cities, ZONE_NAV_LABEL };
