'use strict';

/** Villes d'intervention — Béziers (siège) et communes dans un rayon d'environ 30 km */
const cities = [
  {
    slug: 'beziers',
    name: 'Béziers',
    dept: 'Hérault (34)',
    tag: 'Siège — rayon 30 km',
    lat: 43.341,
    lng: 3.215,
    lead: "SAR Nettoyage est basé à Béziers. Nous intervenons en centre-ville et dans toutes les communes du bassin biterrois pour le nettoyage professionnel de murs intérieurs, façades et traitements anti-moisissure. Devis gratuit sous 15 minutes.",
    communes: ['Centre-ville', 'Les Ayroles', 'Montimaran', 'Saint-James', 'La Madeleine', 'Deveze', 'Fraisse-sur-Agout', 'Cers'],
    img: 'service_exterior.png',
    alt: 'Nettoyage de murs à Béziers',
    cardSub: 'Siège & centre-ville',
  },
  {
    slug: 'serignan',
    name: 'Sérignan',
    dept: 'Hérault (34)',
    tag: 'À ~8 km de Béziers',
    lat: 43.283,
    lng: 3.283,
    lead: "Nettoyage de murs à Sérignan et sur le littoral proche. Humidité marine, moisissures et salissures de façade : intervention rapide depuis notre base à Béziers.",
    communes: ['Centre-ville', 'Plage', 'Pinède', 'Vignerols', 'Les Orpellières', 'Le Grand Travers'],
    img: 'img3.jpg',
    alt: 'Nettoyage de murs à Sérignan',
    cardSub: 'Littoral & centre',
  },
  {
    slug: 'valras-plage',
    name: 'Valras-Plage',
    dept: 'Hérault (34)',
    tag: 'À ~10 km de Béziers',
    lat: 43.25,
    lng: 3.292,
    lead: "Service de nettoyage de murs à Valras-Plage : résidences secondaires, appartements en bord de mer et façades exposées au sel. Déplacement depuis Béziers sous 30 minutes.",
    communes: ['Front de mer', 'Centre', 'Les Vignes', 'La Voilière', 'Les Marines', 'Capiscol'],
    img: 'img2.jpg',
    alt: 'Nettoyage de murs à Valras-Plage',
    cardSub: 'Station balnéaire',
  },
  {
    slug: 'vias',
    name: 'Vias',
    dept: 'Hérault (34)',
    tag: 'À ~12 km de Béziers',
    lat: 43.314,
    lng: 3.417,
    lead: "Nettoyage professionnel de murs à Vias, entre plage et village. Traitement anti-moisissure, fin de bail et façades — équipe SAR au départ de Béziers.",
    communes: ['Centre-ville', 'Vias-Plage', 'Méditerranée', 'Les Saladelles', 'Le Cap', 'Domaine de la Tour'],
    img: 'img3.jpg',
    alt: 'Nettoyage de murs à Vias',
    cardSub: 'Plage & village',
  },
  {
    slug: 'villeneuve-les-beziers',
    name: 'Villeneuve-lès-Béziers',
    dept: 'Hérault (34)',
    tag: 'À ~5 km de Béziers',
    lat: 43.318,
    lng: 3.285,
    lead: "Intervention à Villeneuve-lès-Béziers pour le nettoyage de murs en lotissement, pavillons et copropriétés. Proximité immédiate de notre siège à Béziers.",
    communes: ['Centre', 'Les Mas de la Mer', 'Capiscol', 'Les Écus', 'Domaine des Oliviers', 'Hameau de la Plage'],
    img: 'img4.webp',
    alt: 'Nettoyage de murs à Villeneuve-lès-Béziers',
    cardSub: 'Agglomération biterroise',
  },
  {
    slug: 'agde',
    name: 'Agde',
    dept: 'Hérault (34)',
    tag: 'À ~27 km de Béziers',
    lat: 43.311,
    lng: 3.475,
    lead: "Nettoyage de murs à Agde, Le Cap d'Agde et alentours. Salinité, humidité et traces en extérieur : nos techniciens couvrent le secteur depuis Béziers.",
    communes: ["Le Grau d'Agde", 'Le Cap d\'Agde', 'Centre historique', 'Saint-Vincent', 'Tamarius', 'Richelieu'],
    img: 'service_exterior.png',
    alt: 'Nettoyage de murs à Agde',
    cardSub: 'Cap & centre',
  },
  {
    slug: 'pezenas',
    name: 'Pézenas',
    dept: 'Hérault (34)',
    tag: 'À ~25 km de Béziers',
    lat: 43.461,
    lng: 3.423,
    lead: "Restauration et nettoyage de murs à Pézenas, cité médiévale et communes voisines. Pierres, enduits et peintures anciennes traités avec soin par SAR Nettoyage.",
    communes: ['Centre historique', 'Saint-Jean', 'Nébian', 'Tourbes', 'Pomérols', 'Castelnau-de-Guers'],
    img: 'img6.jpg',
    alt: 'Nettoyage de murs à Pézenas',
    cardSub: 'Cité médiévale',
  },
  {
    slug: 'capestang',
    name: 'Capestang',
    dept: 'Hérault (34)',
    tag: 'À ~18 km de Béziers',
    lat: 43.328,
    lng: 3.044,
    lead: "Nettoyage de murs à Capestang et villages du canal du Midi. Appartements, maisons de village et façades : intervention planifiée depuis notre base biterroise.",
    communes: ['Centre-ville', 'Le Canal', 'Quarante', 'Poilhès', 'Montels', 'Pradelles-en-Val'],
    img: 'img4.webp',
    alt: 'Nettoyage de murs à Capestang',
    cardSub: 'Canal du Midi',
  },
];

const ZONE_NAV_LABEL = "Zone d'intervention";

module.exports = { cities, ZONE_NAV_LABEL };
